[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_movie_review_program = "B3pvs1DpQaNCRPT1VcgcbzuhZbE7GQ43a3gW3Tkdx5rm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/bryan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
